### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by KrGuy** [Wrapper-Offline/Wrapper-Offline-Beta#1]
The uncaught type error in parse.js when loading videos, which was already fixed before the original beta repo was compromised, is back as of this post-recovery build.
![image](https://user-images.githubusercontent.com/84209806/128105861-ecb010eb-d74a-44c2-bfe8-1208f75ba88d.png)
In newer versions of node.js, this can cause NPM crashes.

**Comment by RegularSpark** [comment]
should be fixed as of the tons of updates i've made to the software.
