### ISSUE TITLE
Video is not loading

### ISSUE THREAD

**Issue by michelle1574** [Wrapper-Offline/Wrapper-Offline-Beta#2]
**Describe the bug**
I imported the XML file but it still loads.

**Expected behavior**
Video loads in 2 minutes

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.19044.1477
 - Type: beta

**Additional context**
Video doesn't load

**Comment by RegularSpark** [comment]
should be fixed as of the tons of updates i've made to the software.
