### ISSUE TITLE
Wrapper offline video list refuses to load

### ISSUE THREAD

**Issue by michelle1574** [Wrapper-Offline/Wrapper-Offline-Beta#3]
**Describe the bug**
Wrapper offline video list refuses to load.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/70703680/131505524-3ae1544a-d054-4b6f-8956-e8f25cb08a8e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chromium from Goanimate
 - OS Version 10.0.19044.1477
 - Wrapper offline version beta

**Additional context**
Please help me because i want to make video and watch it.

**Comment by funbuket9** [comment]
Having this exact same issue also. Happens every time even though I have a strong internet connection.
